//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.11
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.ReportingServices.FindRenderSave.Properties {
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses")]
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.FindRenderSave.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "an error occurred:".
        /// </summary>
        public static string genericErrorMessage {
            get {
                return ResourceManager.GetString("genericErrorMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Application Error".
        /// </summary>
        public static string genericErrorMessageBoxTitle {
            get {
                return ResourceManager.GetString("genericErrorMessageBoxTitle", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Please enter a valid search string.".
        /// </summary>
        public static string invalidSearchStringErrorMessage {
            get {
                return ResourceManager.GetString("invalidSearchStringErrorMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Invalid Search String".
        /// </summary>
        public static string invalidSearchStringMessageBoxTitle {
            get {
                return ResourceManager.GetString("invalidSearchStringMessageBoxTitle", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Unable to save the report from this application because one or more parameters for the report are missing default values.".
        /// </summary>
        public static string missingDefaultParametersErrorMessage {
            get {
                return ResourceManager.GetString("missingDefaultParametersErrorMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Missing Default Parameters".
        /// </summary>
        public static string missingDefaultParametersMessageBoxTitle {
            get {
                return ResourceManager.GetString("missingDefaultParametersMessageBoxTitle", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "No items matching your search criteria were found.".
        /// </summary>
        public static string noItemsFoundInfoMessage {
            get {
                return ResourceManager.GetString("noItemsFoundInfoMessage", _resCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to "Items Not Found".
        /// </summary>
        public static string noItemsFoundMessageBoxTitle {
            get {
                return ResourceManager.GetString("noItemsFoundMessageBoxTitle", _resCulture);
            }
        }
    }
}
