'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.11
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.IO
Imports System.Resources

Namespace My.Resources
    
    'This class was auto-generated by the Strongly Typed Resource Builder
    'class via a tool like ResGen or Visual Studio.NET.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Microsoft.VisualBasic.HideModuleName()>  _
    Module MyResources
        
        Private _resMgr As System.Resources.ResourceManager
        
        Private _resCulture As System.Globalization.CultureInfo
        
        '''<summary>
        '''   Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As System.Resources.ResourceManager
            Get
                If (_resMgr Is Nothing) Then
                    Dim temp As System.Resources.ResourceManager = New System.Resources.ResourceManager("Microsoft.Samples.ReportingServices.FindRenderSave.MyResources", GetType(MyResources).Assembly)
                    _resMgr = temp
                End If
                Return _resMgr
            End Get
        End Property
        
        '''<summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        '''</summary>
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As System.Globalization.CultureInfo
            Get
                Return _resCulture
            End Get
            Set
                _resCulture = value
            End Set
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "an error occurred:".
        '''</summary>
        Public ReadOnly Property genericErrorMessage() As String
            Get
                Return ResourceManager.GetString("genericErrorMessage", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Application Error".
        '''</summary>
        Public ReadOnly Property genericErrorMessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("genericErrorMessageBoxTitle", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Please enter a valid search string.".
        '''</summary>
        Public ReadOnly Property invalidSearchStringErrorMessage() As String
            Get
                Return ResourceManager.GetString("invalidSearchStringErrorMessage", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Invalid Search String".
        '''</summary>
        Public ReadOnly Property invalidSearchStringMessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("invalidSearchStringMessageBoxTitle", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Unable to save the report from this application because one or more parameters for the report are missing default values.".
        '''</summary>
        Public ReadOnly Property missingDefaultParametersErrorMessage() As String
            Get
                Return ResourceManager.GetString("missingDefaultParametersErrorMessage", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Missing Default Parameters".
        '''</summary>
        Public ReadOnly Property missingDefaultParametersMessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("missingDefaultParametersMessageBoxTitle", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "No items matching your search criteria were found.".
        '''</summary>
        Public ReadOnly Property noItemsFoundInfoMessage() As String
            Get
                Return ResourceManager.GetString("noItemsFoundInfoMessage", _resCulture)
            End Get
        End Property
        
        '''<summary>
        '''   Looks up a localized string similar to "Items Not Found".
        '''</summary>
        Public ReadOnly Property noItemsFoundMessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("noItemsFoundMessageBoxTitle", _resCulture)
            End Get
        End Property
    End Module
End Namespace
