<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2007:MarkAssembliesWithReliabilityContract")> 

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope:="member", Target:="Microsoft.Samples.ReportingServices.FsiDataExtension.FsiTransaction.Microsoft.ReportingServices.DataProcessing.IDbTransaction.Rollback():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiTransaction.Microsoft.ReportingServices.DataProcessing.IDbTransaction.Commit():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.Read():System.Boolean")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.GetValue(System.Int32):System.Object")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.GetOrdinal(System.String):System.Int32")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.GetName(System.Int32):System.String")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.GetFieldType(System.Int32):System.Type")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader.Microsoft.ReportingServices.DataProcessing.IDataReader.FieldCount")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataParameterCollection.Microsoft.ReportingServices.DataProcessing.IDataParameterCollection.Add(Microsoft.ReportingServices.DataProcessing.IDataParameter):System.Int32")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataParameter.Microsoft.ReportingServices.DataProcessing.IDataParameter.Value")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataParameter.Microsoft.ReportingServices.DataProcessing.IDataParameter.ParameterName")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.Interfaces.IExtension.SetConfiguration(System.String):System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.Interfaces.IExtension.LocalizedName")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.UserName")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.Password")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.IntegratedSecurity")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.Impersonate")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.Open():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.CreateCommand():Microsoft.ReportingServices.DataProcessing.IDbCommand")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.ConnectionTimeout")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.ConnectionString")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.Close():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnection.BeginTransaction():Microsoft.ReportingServices.DataProcessing.IDbTransaction")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.Transaction")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.Parameters")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.CreateParameter():Microsoft.ReportingServices.DataProcessing.IDataParameter")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.CommandType")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.CommandText")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.CommandTimeout")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.Cancel():System.Void")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope := "namespace", Target := "FsiDataExtension")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2123:OverrideLinkDemandsShouldBeIdenticalToBase", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiCommand.Microsoft.ReportingServices.DataProcessing.IDbCommand.ExecuteReader(Microsoft.ReportingServices.DataProcessing.CommandBehavior):Microsoft.ReportingServices.DataProcessing.IDataReader")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1801:AvoidUnusedParameters", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection..ctor(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.Impersonate")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.Password")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection.Microsoft.ReportingServices.DataProcessing.IDbConnectionExtension.UserName")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataParameterCollection.Microsoft.ReportingServices.DataProcessing.IDataParameterCollection.Add(Microsoft.ReportingServices.DataProcessing.IDataParameter):System.Int32")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1801:AvoidUnusedParameters", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader..ctor(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader..ctor(System.String,Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1801:AvoidUnusedParameters", Scope := "member", Target := "Microsoft.Samples.ReportingServices.FsiDataExtension.FsiDataReader..ctor(System.String,Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection)")> 


<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection..ctor(System.String)")> 
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1805:DoNotInitializeUnnecessarily", Scope:="member", Target:="Microsoft.Samples.ReportingServices.FsiDataExtension.FsiConnection..ctor()")> 
