'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version:2.0.40607.11
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SettingNamespace
    
    <System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses")> Partial NotInheritable Class SettingClass
        Inherits System.Configuration.ApplicationSettingsBase

        Private Shared m_Value As SettingClass

        Private Shared m_SyncObject As Object = New Object

        <System.Diagnostics.DebuggerNonUserCode()> _
        Public Shared ReadOnly Property Value() As SettingClass
            Get
                If (SettingClass.m_Value Is Nothing) Then
                    System.Threading.Monitor.Enter(SettingClass.m_SyncObject)
                    If (SettingClass.m_Value Is Nothing) Then
                        Try
                            SettingClass.m_Value = New SettingClass
                        Finally
                            System.Threading.Monitor.Exit(SettingClass.m_SyncObject)
                        End Try
                    End If
                End If
                Return SettingClass.m_Value
            End Get
        End Property
    End Class
End Namespace
